#! /bin/bash

# Runs jest which scans for `*.spec.ts` files
# Jest config is in package.json

source .env

# Run tests on server
# JEST_TEST_ENV=node ./node_modules/.bin/jest --verbose --detectOpenHandles --config .jest.config.js

# Run tests on client
./node_modules/.bin/jest --verbose --detectOpenHandles --config .jest.config.js
